const w1 = require("../assets/images/smartwatch1.png");
const w2 = require("../assets/images/rolex1.png");
const w3 = require("../assets/images/gshock1.png");
const w4 = require("../assets/images/golden-woman.png");
const w5 = require("../assets/images/casio1.png");
const w6 = require("../assets/images/smartwatch2.png");
const w7 = require("../assets/images/hublot1.png");
const w8 = require("../assets/images/apple1.png");

export const WATCHES_LIST = [
  {
    id: 1,
    name: "Smartwatch Alpha",
    description: "Une smartwatch moderne avec des fonctionnalités avancées.",
    price: 299.99,
    // promotionPrice: 249.99,
    stock: 50,
    color: "Black",
    type: "smartwatch",
    material: "plastic",
    target: "unisex",
    image: w1,
    brand: "TechBrand",
  },
  {
    id: 2,
    name: "Classic Rolex Watch",
    description:
      "Montre classique en cuir, parfaite pour les occasions formelles.",
    price: 199.99,
    promotionPrice: 149.99,
    stock: 30,
    color: "Black",
    type: "classic",
    material: "leather",
    target: "men",
    image: w2,
    brand: "Rolex",
  },
  {
    id: 3,
    name: "G SHOCK Fitness Tracker",
    description: "Suivez votre activité physique avec ce tracker sportif.",
    price: 129.99,
    promotionPrice: 99.99,
    stock: 75,
    color: "Orange",
    type: "sport",
    material: "plastic",
    target: "men",
    image: w3,
    brand: "G SHOCK",
  },
  {
    id: 4,
    name: "Gold Plated Classic Watch",
    description:
      "Montre classique plaquée or, alliant élégance et sophistication.",
    price: 399.99,
    promotionPrice: 349.99,
    stock: 20,
    color: "Gold",
    type: "classic",
    material: "gold",
    target: "women",
    image: w4,
    brand: "LuxuryWatches",
  },
  {
    id: 5,
    name: "Silver Casio Sport Watch",
    description:
      "Montre sportive en acier inoxydable, idéale pour les activités en extérieur.",
    price: 249.99,
    // promotionPrice: 199.99,
    stock: 40,
    color: "Silver",
    type: "sport",
    material: "silver",
    target: "men",
    image: w5,
    brand: "Casio",
  },
  {
    id: 6,
    name: "Smart Fitness Watch Pro",
    description: "Montre intelligente avec suivi de la santé et notifications.",
    price: 349.99,
    promotionPrice: 299.99,
    stock: 25,
    color: "Pink",
    type: "smartwatch",
    material: "iron",
    target: "women",
    image: w6,
    brand: "HealthTech",
  },
  {
    id: 7,
    name: "Hublot Casual Watch",
    description: "Montre décontractée en plastique, légère et colorée.",
    price: 49.99,
    promotionPrice: 39.99,
    stock: 100,
    color: "Navy",
    type: "classic",
    material: "leather",
    target: "men",
    image: w7,
    brand: "Hublot",
  },
  {
    id: 8,
    name: "Apple Watch s1",
    description:
      "Smartwatch haut de gamme avec design élégant et fonctionnalités complètes.",
    price: 599.99,
    // promotionPrice: 499.99,
    stock: 15,
    color: "Orange",
    type: "smartwatch",
    material: "plastic",
    target: "unisex",
    image: w8,
    brand: "Apple",
  },
];
